CREATE TABLE IF NOT EXISTS `products` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(200) NOT NULL,
    `slug` VARCHAR(220) NOT NULL UNIQUE,
    `description` TEXT NULL,
    `short_description` VARCHAR(300) NULL,
    `price` DECIMAL(10, 2) NOT NULL,
    `compare_price` DECIMAL(10, 2) NULL,
    `sku` VARCHAR(50) NULL UNIQUE,
    `stock` INT NOT NULL DEFAULT 0,
    `category_id` INT UNSIGNED NULL,
    `brand_id` INT UNSIGNED NULL,
    `is_active` TINYINT(1) NOT NULL DEFAULT 1,
    `is_featured` TINYINT(1) NOT NULL DEFAULT 0,
    `views_count` INT UNSIGNED NOT NULL DEFAULT 0,
    `meta_title` VARCHAR(200) NULL,
    `meta_description` VARCHAR(300) NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_products_name` (`name`),
    INDEX `idx_products_category` (`category_id`),
    INDEX `idx_products_brand` (`brand_id`),
    INDEX `idx_products_is_active` (`is_active`),
    INDEX `idx_products_is_featured` (`is_featured`),
    INDEX `idx_products_price` (`price`),
    FULLTEXT INDEX `ft_products_search` (`name`, `description`, `short_description`),
    CONSTRAINT `fk_products_category` FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `fk_products_brand` FOREIGN KEY (`brand_id`) REFERENCES `brands`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
